### ISSUE TITLE
cant test anything for QA because cant login with discord to bethero

### ISSUE THREAD

**Issue by zero10xy** [BetHero-pro/BetHero#2]
![Image](https://user-images.githubusercontent.com/9776377/241821211-251c3bbc-87f9-43fc-89da-1c6f1ba3819c.png)

**Comment by zero10xy** [comment]
cant login

**Comment by zero10xy** [comment]
ho i think why - as sent: "update: right now stopping servers to avoid wasting credits"

**Comment by nooandpro77** [comment]
this has been fixed
