### ISSUE TITLE
bug = after trying to login with discord, it send to welcome page and not into the list page, also in mobile browser its not working...

### ISSUE THREAD

**Issue by zero10xy** [BetHero-pro/BetHero#4]
![Image](https://user-images.githubusercontent.com/9776377/240771162-6aeb1701-a951-481d-921f-850c07062030.png)

**Comment by zero10xy** [comment]
again when login to discord it go to welcome page and not to quest list page
when login it need to go to quest list page not to welcome page

**Comment by nooandpro77** [comment]
this is issue has been fixed refer to new version please
