### ISSUE TITLE
version 0.1.1

### ISSUE THREAD

**Issue by zero10xy** [BetHero-pro/BetHero#9]
update the text of the version to = 0.1.1

![Image](https://user-images.githubusercontent.com/9776377/243505372-2a207077-8241-4d4d-9a2a-a6b4db841725.png)

**Comment by zero10xy** [comment]
how its going?

**Comment by nooandpro77** [comment]
please close the issue it is fixed

**Comment by nooandpro77** [comment]
since it has been fixed i am closing the issue now
